//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagement
{
    using System;
    
    public enum KitchenRole : int
    {
        HeadChef = 0,
        LineChef = 1,
        Chef = 2,
        Dessert = 3
    }
}
